### ISSUE TITLE
Importing from phpBB 3.1.4

### ISSUE THREAD

**Issue by antstanley** [psychobunny/nodebb-plugin-import-phpbb#7]
I had two unknown column errors importing from phpBB 3.1.4.  I'm assuming they changed the table schema whilst upgrading.

The errors were in the topics table, with the field topic_approved missing, and in the posts table with the field post_approved missing.  I fixed it by running these SQL commands..

ALTER TABLE phpbb_topics ADD topic_approved INT;
UPDATE phpbb_topics SET topic_approved = 0;

ALTER TABLE phpbb_posts ADD post_approved INT;
UPDATE phpbb_posts SET post_approved = 0;

Essentially I just created the missing columns, and set them to 0. Re-ran the import and it worked!

**Comment by psychobunny** [comment]
Cool :) I'll move this information into the wiki/docs, thanks for letting me know

**Comment by tiazzz** [comment]
I see this is a closed issue, but the flaw still exists. After googling around I found a few dodgy sources mentioning 'topic_approved'. Seems this is renamed to 'topic_visibility' in 3.1.0.

Since 3.1.X is the latest and greatest from phpBB, shouldn't the importer be updated? Or set to check phpBB version and handle both or something.

PS: topic_approved = 0 should mean that the topic is invisible in phpBB. Same for post. I guess the importer doesn't handle this but setting it to '1' instead makes it consistent with phpBB.

https://wiki.phpbb.com/Practical.Displaying_posts_and_topics_on_external_pages
https://www.phpbb.com/community/viewtopic.php?f=461&t=233

**Comment by akhoury** [comment]
@tiazzz i don't see why we can't fix that, publish and document which version of importer to use with which phpbb version - 

@psychobunny can you add me as a collaborator here so i won't have to bother you with the changes?

**Comment by psychobunny** [comment]
@akhoury done, thanks

**Comment by tiazzz** [comment]
I've done the hack @antstanley suggested and still see some errors in the import. I commented out some code that the import got stuck on, with output.log looking like this:

    importer.warn purgeCategories+Topics+PostsStart : [[error:no-privileges]]
    [nodebb-plugin-import] importer.warn purgeCategories+Topics+PostsStart : [[error:no-privileges]]
    importer.progress { count: 1, total: 1, percentage: 100 }
    importer.phase { phase: 'purgeCategories+Topics+PostsDone', data: undefined }
    importer.phase { phase: 'purgeUsersStart', data: undefined }

I got an error with plugins directly from npm:

    25/10 21:20 [22859] - error: TypeError: Object 78 has no method 'toUpperCase'
    at /home/stcn/node_modules/nodebb/node_modules/nodebb-plugin-import-phpbb/index.js:204:61
    at Array.forEach (native)
    at Query._callback (/home/stcn/node_modules/nodebb/node_modules/nodebb-plugin-import-phpbb/index.js:203:22)
    at Query.Sequence.end (/home/stcn/node_modules/nodebb/node_modules/nodebb-plugin-import-phpbb/node_modules/mysql/lib/protocol/sequences/Sequence.js:96:24)
    at Query._handleFinalResultPacket (/home/stcn/node_modules/nodebb/node_modules/nodebb-plugin-import-phpbb/node_modules/mysql/lib/protocol/sequences/Query.js:143:8)
    at Query.EofPacket (/home/stcn/node_modules/nodebb/node_modules/nodebb-plugin-import-phpbb/node_modules/mysql/lib/protocol/sequences/Query.js:127:8)
    at Protocol._parsePacket (/home/stcn/node_modules/nodebb/node_modules/nodebb-plugin-import-phpbb/node_modules/mysql/lib/protocol/Protocol.js:270:23)
    at Parser.write (/home/stcn/node_modules/nodebb/node_modules/nodebb-plugin-import-phpbb/node_modules/mysql/lib/protocol/Parser.js:77:12)
    at Protocol.write (/home/stcn/node_modules/nodebb/node_modules/nodebb-plugin-import-phpbb/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/home/stcn/node_modules/nodebb/node_modules/nodebb-plugin-import-phpbb/node_modules/mysql/lib/Connection.js:82:28)

I tried commenting out line 204 in index.js in nodebb-plugin-import-phpbb and the import goes a bit further, but then get stuck later on:

    nodebb-plugin-import] importer.success Importing 26142 topics.
    25/10 21:30 [23074] - error: TypeError: Object Nytt forum!! has no method 'replace'
    at Object.module.exports.utils.slugify (/home/stcn/node_modules/nodebb/public/src/utils.js:81:14)
    at /home/stcn/node_modules/nodebb/node_modules/nodebb-plugin-import/server/importer.js:1325:32
    at /home/stcn/node_modules/nodebb/node_modules/nodebb-plugin-import/node_modules/async/lib/async.js:251:17
    at done (/home/stcn/node_modules/nodebb/node_modules/nodebb-plugin-import/node_modules/async/lib/async.js:132:19)
    at /home/stcn/node_modules/nodebb/node_modules/nodebb-plugin-import/node_modules/async/lib/async.js:32:16
    at /home/stcn/node_modules/nodebb/node_modules/nodebb-plugin-import/node_modules/async/lib/async.js:248:21
    at /home/stcn/node_modules/nodebb/node_modules/nodebb-plugin-import/node_modules/async/lib/async.js:572:34
    at /home/stcn/node_modules/nodebb/node_modules/nodebb-plugin-import/server/importer.js:1232:12
    at /home/stcn/node_modules/nodebb/node_modules/nodebb-plugin-import/server/data.js:265:5
    at try_callback (/home/stcn/node_modules/nodebb/node_modules/redis/index.js:573:9)

"Nytt forum!!" is the first topic created in the forum I'm trying to import.

Any ideas?
