### ISSUE TITLE
An issue with phpBB 2.0.23

### ISSUE THREAD

**Issue by Nicofisi** [psychobunny/nodebb-plugin-import-phpbb#8]
Hi, what are the versions of phpBB supported by this plugin? With phpBB 2.0.23, I get this:
```
[nodebb-plugin-import-phpbb] { Error: ER_BAD_FIELD_ERROR: Unknown column 'phpbb_users.username_clean' in 'field list'
    at Query.Sequence._packetToError (/home/inedia/NodeBB/node_modules/mysql/lib/protocol/sequences/Sequence.js:48:14)
    at Query.ErrorPacket (/home/inedia/NodeBB/node_modules/mysql/lib/protocol/sequences/Query.js:82:18)
    at Protocol._parsePacket (/home/inedia/NodeBB/node_modules/mysql/lib/protocol/Protocol.js:270:23)
```
^ there is no "username_clean" column in my phpbb_users table. The only columns are:
```
user_id
user_active
username
user_password
user_session_time
user_session_page
user_lastvisit
user_regdate
user_level
user_posts
user_timezone
user_style
user_lang
user_dateformat
user_new_privmsg
user_unread_privmsg
user_last_privmsg
user_emailtime
user_viewemail
user_attachsig
user_allowhtml
user_allowbbcode
user_allowsmile
user_allowavatar
user_allow_pm
user_allow_viewonline
user_notify
user_notify_pm
user_popup_pm
user_rank
user_avatar
user_avatar_type
user_email
user_icq
user_website
user_from
user_sig
user_sig_bbcode_uid
user_aim
user_yim
user_msnm
user_occ
user_interests
user_actkey
user_newpasswd
user_login_tries
user_last_login_try
```

**Comment by Nicofisi** [comment]
I guess that I should set up a new forum, with version of phpBB like 3.0+, and then try migrating to NodeBB again, after the database is updated? But which versions are supported?
